#Survivor - Sauvegarde automatique
#Tue Feb 24 13:04:01 CET 2026
records.bestTimeTicks=0
player.gold=0
player.maxHp=100
settings.fullscreen=false
player.attackRange=200
records.bestScore=0
settings.showRange=true
player.damage=15
player.attackRate=60
settings.difficulty=EASY
state.hasActiveGame=true
