#Survivor - Sauvegarde automatique
#Tue Feb 24 13:48:42 CET 2026
settings.fullscreen=true
upgrade.speed=0
upgrade.hp=0
upgrade.lifeSteal=0
upgrade.critDmg=0
records.bestTimeTicks=0
player.gold=95
upgrade.damage=0
upgrade.range=0
settings.showRange=true
upgrade.crit=0
settings.difficulty=EASY
